---
specfile_path: hello.spec
synced_files:
  - hello.spec
upstream_package_name: hello
downstream_package_name: hello
jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-rawhide-x86_64
  actions:
    post-upstream-clone: "ls /*"
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
    - fedora-32-x86_64
  actions:
    post-upstream-clone: 'bash -c "ls /*"'